-- Local baseline fixture only. Never run this file against Production.
-- It intentionally models the pre-hardening public state for migration tests.
create extension if not exists pgcrypto;

create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  booking_no text not null unique,
  booking_date date not null,
  period text not null check (period in ('morning', 'afternoon')),
  hours integer not null,
  graduates integer not null,
  fullname text not null,
  phone text not null,
  line text,
  facebook text,
  university text not null,
  faculty text not null,
  note text,
  total_price integer not null,
  slip_url text,
  status text not null default 'pending' check (
    status in ('draft', 'pending', 'paid', 'confirmed', 'completed', 'cancelled')
  ),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  start_time text,
  end_time text,
  deposit_amount integer not null default 1000,
  remaining_amount integer
);

create table if not exists public.blocked_slots (
  id uuid primary key default gen_random_uuid(),
  booking_date date not null,
  period text not null check (period in ('morning', 'afternoon')),
  reason text,
  created_at timestamptz not null default now(),
  unique (booking_date, period)
);

create table if not exists public.blocked_dates (
  id uuid primary key default gen_random_uuid(),
  booking_date date not null unique,
  reason text,
  created_at timestamptz default now()
);

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  page text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists unique_active_booking_slot
on public.bookings (booking_date, period)
where status in ('pending', 'confirmed');

alter table public.bookings enable row level security;
alter table public.blocked_slots enable row level security;
alter table public.blocked_dates enable row level security;
alter table public.page_views enable row level security;

insert into storage.buckets (id, name, public)
values ('slips', 'slips', true), ('payment-slips', 'payment-slips', true)
on conflict (id) do update set public = excluded.public;
